export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const GET_EVENT_REQUESTED = 'GET_EVENT_REQUESTED';
export const GET_EVENT_REJECTED = 'GET_EVENT_REJECTED';
export const GET_EVENT_FULFILLED = 'GET_EVENT_FULFILLED';
// export const LOAD_EVENTS_FULFILLED = 'LOAD_EVENTS_FULFILLED';

export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
